apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-symbiosis
  name: nginx-symbiosis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-symbiosis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-symbiosis
    spec:
      containers:
        - image: gcr.io/sage-ripple-146416/github.com/t3ratech/symbiosis
          imagePullPolicy: IfNotPresent
          name: symbiosis-sha256-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: nginx-symbiosis
  name: nginx-symbiosis-hpa-ledz
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-symbiosis
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: nginx-symbiosis
  name: nginx-symbiosis-service
  namespace: default
spec:
  clusterIP: 10.8.11.155
  externalTrafficPolicy: Cluster
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: wildfly-http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: wildfly-https
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: jenkins
      port: 17505
      protocol: TCP
      targetPort: 17505
  selector:
    app: nginx-symbiosis
  sessionAffinity: None
  type: LoadBalancer
